# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'aaa' do

 pod 'MJRefresh', '~> 3.1.12'

  target 'aaaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'aaaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
